### ISSUE TITLE
a conflict with `@typescript-eslint/no-floating-promises` rule

### ISSUE THREAD

**Issue by Kjaer** [ota-meshi/yaml-eslint-parser#154]
Hey @ota-meshi,

I have encountered this problem after I install the `yaml-eslint-parser`,

```sh
ESLint: 8.43.0

Error: Error while loading rule '@typescript-eslint/no-floating-promises': You have used a rule which requires parserServices to be generated.
You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting /my-project/integrationTests/codegen.yml
    at Object.getParserServices (/my-project/integrationTests/node_modules/@typescript-eslint/utils/dist/eslint-utils/getParserServices.js:15:15)
    at create (/my-project/integrationTests/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-floating-promises.js:72:37)
    at Object.create (/my-project/integrationTests/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:41:20)
    at createRuleListeners (/my-project/integrationTests/node_modules/eslint/lib/linter/linter.js:870:21)
    at /my-project/integrationTests/node_modules/eslint/lib/linter/linter.js:1040:110
    at Array.forEach (<anonymous>)
    at runRules **(/my-project/integrationTests/node_modules/eslint/lib/linter/linter.js:977:34)**
    at Linter._verifyWithoutProcessors (/my-project/integrationTests/node_modules/eslint/lib/linter/linter.js:1330:31)
    at Linter._verifyWithConfigArray (/my-project/integrationTests/node_modules/eslint/lib/linter/linter.js:1706:21)
    at Linter.verify (/my-project/integrationTests/node_modules/eslint/lib/linter/linter.js:1412:65)
```

this is my `eslintrc.js` file's content:
```js
const path = require('path');

module.exports = {
	env: {
		browser: true,
		es2021: true
	},
	extends: [
		'eslint:recommended',
		'plugin:@typescript-eslint/recommended',
		'plugin:yml/standard',
		'plugin:yml/prettier'
	],
	overrides: [
		{
			files: ['*.yaml', '*.yml'],
			parser: 'yaml-eslint-parser'
		}
	],
	parser: '@typescript-eslint/parser',

	parserOptions: {
		ecmaVersion: 'latest',
		sourceType: 'module',
		project: path.join(__dirname, 'tsconfig.json')
	},
	plugins: ['@typescript-eslint'],
	rules: {
		'@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
		'no-mixed-spaces-and-tabs': 'off',
		'@typescript-eslint/no-floating-promises': 'error'
	}
};
```

If I remove `'@typescript-eslint/no-floating-promises': 'error'` rule from `rules` my eslint works just fine.

any clue why this error occured?

(I am happy to assist you further for this bug)

**Comment by ota-meshi** [comment]
Sorry for the late reply.
The rules that use their type information are not compatible with YAML files. Either turn those rules off in the YAML section in `overrides`, or add a section for using type information in `overrides` and use `files: ['*.ts', '*.tsx', '*.mts', '*.cts']` and `'@typescript-eslint/no-floating-promises'` there please.
